# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

theme = "transparent"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

