# SPDX-FileCopyrightText: 2026 Copyright (C) 2024-2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

inherits = "ayu_mirage"

["ui.background"]

["ui.help"]

["ui.menu"]

["ui.statusline"]

["ui.text"]
